### ISSUE TITLE
error

### ISSUE THREAD

**Issue by androiddevcoding** [k3muri84/generate-changelog#8]
![image](https://user-images.githubusercontent.com/11345578/109658803-6ecea980-7b80-11eb-8cb8-594c064e5f3e.png)

**Comment by k3muri84** [comment]
hey @nailshakurov, can u share the full traceback?
Are u sure authentication works with auth provided? or do you have other requirements for the jira server like oauth or something else? You can also try to use basic_auth instead of auth in line 22 of the script.

**Comment by androiddevcoding** [comment]
> hey @nailshakurov, can u share the full traceback?
> Are u sure authentication works with auth provided? or do you have other requirements for the jira server like oauth or something else? You can also try to use basic_auth instead of auth in line 22 of the script.

![image](https://user-images.githubusercontent.com/11345578/109863960-b554fe80-7c7b-11eb-9973-05bac1b414c2.png)
Thanks for the answer, it worked like that. Thanks for the script. Good luck!

**Comment by k3muri84** [comment]
cool thx for feedback, added a link to auth modes in the user config section

**Comment by k3muri84** [comment]
ah it seems with jira 3.0.1 this is a required thing so i'm going to change the default for everyone, see also https://github.com/pycontribs/jira/issues/1035
